version: '3'

services:

    db:
        image: mariadb:10.1
        volumes:
            - "./.data/front_db_video:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go
            MYSQL_USER: root
            MYSQL_PASSWORD: admin
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - "8000:80"
